Make tweak-service independend from octoprint

diff --git a/preprintservice_src/Dockerfile b/preprintservice_src/Dockerfile
--- a/preprintservice_src/Dockerfile
+++ b/preprintservice_src/Dockerfile
@@ -51,8 +51,9 @@ RUN mkdir -p /home/slic3r/.local/share/
 ADD . /src/.
 
 # Clone if Tweaker-3 doesn't exist, and pull.
-RUN rm -r /src/Tweaker-3  > /dev/null 2>&1 || true \
-  && git clone https://github.com/ChristophSchranz/Tweaker-3 /src/Tweaker-3 \
+RUN ls /src/Tweaker-3/README.md  > /dev/null 2>&1  \
+  || (echo "Tweaker not found, cloning repository" \
+    && git clone https://github.com/ChristophSchranz/Tweaker-3 /src/Tweaker-3) \
   && cd /src/Tweaker-3 \
   && git pull
 
